name: website
version: '0.1.0.0'
synopsis: Build system and source files for https://cressent.org
author: Cyril Cressent
maintainer: cyril@cressent.org
license: MIT
homepage: https://github.com/ccressent/cressent.org
bug-reports: https://github.com/ccressent/cressent.org/issues

executables:
  website:
    main: website.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -O2
    - -Wall
    dependencies:
    - aeson
    - base >=4.7 && < 5
    - containers
    - lens
    - lens-aeson
    - mustache
    - pandoc
    - shake
    - slick
    - text
    - time
